### ISSUE TITLE
Encoding error when trying to save a file on Windows

### ISSUE THREAD

**Issue by agustindangelo** [t-wolfeadam/AnyLogic-Pypeline#20] opened 2021-09-28 16:24 UTC
Hello!

I am getting an error when I try to execute the following code to save an agent's information to a json file:

```
String json = pyCommunicator.toJson(this);
pyCommunicator.run(
	"with open('./model-output/output-exp%s-rep%s.json', 'w', encoding='ISO-8859-1') as f:", 
	String.format("  f.write('''%s''')", json),
	"  f.close()"
);
```
![image](https://user-images.githubusercontent.com/52323045/135126973-e4bc3875-e89b-46ff-aac8-91081d903abd.png)

Anylogic console:
```
at com.anylogic.engine.Engine.error(Unknown Source)
	at com.anylogic.engine.Agent.error(Unknown Source)
	at com.anylogic.engine.Utilities.error(Unknown Source)
	at com.anylogic.libraries.pypeline.PyCommunicator.run(PyCommunicator.java:583)
	at com.anylogic.libraries.pypeline.PyCommunicator.run(PyCommunicator.java:598)
	at prueba.Main.saveOutput(Main.java:640)
	at prueba.ParametersVariation.onEngineFinished(ParametersVariation.java:388)
```

It only occurs on Windows. I can run it on Linux with no errors, but when inspecting the output json file, I see that latin characters (like ñ or á) contained in the Anylogic model are replaced with question marks.
I think it is somewhat related to encodings, but I have already tried with `utf-8`, `utf-16` and `ISO-8859-1` on the `open()` code line this way:
`"with open('./model-output/output-exp%s-rep%s.json', 'w', encoding='ISO-8859-1') as f:",`

Thank you😄

**Comment by t-wolfeadam** [comment] 2021-09-29 00:05
Hi! 

Looks like my lack of knowledge about handling various string encodings caught up to me! 

After looking into this, the problem is with my Python code that handles incoming binary data from Java (i.e., AL models). I have it set to only convert using utf-8 ([reference](https://github.com/t-wolfeadam/AnyLogic-Pypeline/blob/master/Source/AL-Pypeline%20Library/Pypeline%20Library.alp#L980)) - what I assumed would be ok for everything - causing it to fail when any latin characters are passed.

For a fix, I've added extra handling to use ISO-8859-1 as a fallback. 

And to validate this, I looped thru all characters in utf-8, utf-16, and iso-8859-1 (thanks to [this SO post](https://stackoverflow.com/a/5389648)) and checked whether Pypeline would throw an error when running: `pyCommunicator.run(String.format("x='%s'", chr));` In each, only 5 failed, but they were due to unhandled syntax reasons (e.g., newline characters, single quote, backslash).

I've pushed the changes but will include this as part of the next release. For convenience, you can download an updated jar file: [Pypeline.zip](https://github.com/t-wolfeadam/AnyLogic-Pypeline/files/7247948/Pypeline.zip). I'm closing but feel free to let me know if you still have issues with it!

**Closed by t-wolfeadam** 2021-09-29 00:05 UTC
